### ISSUE TITLE
20.10 "Groovy Gorilla" Wallpaper

### ISSUE THREAD

**Issue by bluesabre** [Xubuntu/xubuntu-artwork#1]
User Interface Freeze is September 17th.
https://discourse.ubuntu.com/t/groovy-gorilla-release-schedule/15531

**Comment by JPeisach** [comment]
Shouldn't need to worry about this until August or when 20.04.1 get's released IMO

**Comment by farhatizakaria** [comment]
@ItzSwirlz Yeh, that's good idea 💡
